"""redact news tables

Revision ID: 13726f3c42d6
Revises: ecb5f8802d31
Create Date: 2026-06-28 19:51:24.055177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13726f3c42d6'
down_revision: Union[str, Sequence[str], None] = 'ecb5f8802d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_to_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['news_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('news_to_base')
    op.add_column('news', sa.Column('parser_source', sa.String(length=50), nullable=True))
    op.add_column('news', sa.Column('content_type', sa.Enum('news', 'update', 'insight', name='news_content_type_enum'), nullable=False))
    op.add_column('news', sa.Column('news_type', sa.Enum('new_model', 'certificate', 'compatibility', 'general', name='news_type_enum'), nullable=False))
    op.add_column('news', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('url_hash', sa.String(length=32), nullable=False))
    op.add_column('news', sa.Column('content_hash', sa.String(length=32), nullable=True))
    op.add_column('news', sa.Column('image_local_path', sa.String(length=500), nullable=True))
    op.add_column('news', sa.Column('image_downloaded', sa.Boolean(), nullable=False))
    op.add_column('news', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('source_published_at', sa.DateTime(), nullable=True))
    op.alter_column('news', 'title',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('news', 'content_original',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('news', 'title_deepseek',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=True)
    op.alter_column('news', 'content_deepseek',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('news', 'source_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('news', 'image_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('news', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('news', 'published_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_index('ix_news_content_type', 'news', ['content_type'], unique=False)
    op.create_index('ix_news_news_type', 'news', ['news_type'], unique=False)
    op.create_index('ix_news_published', 'news', ['is_published'], unique=False)
    op.create_index('ix_news_source_date', 'news', ['source_published_at'], unique=False)
    op.create_index(op.f('ix_news_url_hash'), 'news', ['url_hash'], unique=True)
    op.create_unique_constraint(None, 'news', ['source_url'])
    op.create_foreign_key(None, 'news', 'brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_index(op.f('ix_news_url_hash'), table_name='news')
    op.drop_index('ix_news_source_date', table_name='news')
    op.drop_index('ix_news_published', table_name='news')
    op.drop_index('ix_news_news_type', table_name='news')
    op.drop_index('ix_news_content_type', table_name='news')
    op.alter_column('news', 'published_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('news', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('news', 'image_url',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('news', 'source_url',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('news', 'content_deepseek',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('news', 'title_deepseek',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('news', 'content_original',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('news', 'title',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('news', 'source_published_at')
    op.drop_column('news', 'brand_id')
    op.drop_column('news', 'image_downloaded')
    op.drop_column('news', 'image_local_path')
    op.drop_column('news', 'content_hash')
    op.drop_column('news', 'url_hash')
    op.drop_column('news', 'summary')
    op.drop_column('news', 'news_type')
    op.drop_column('news', 'content_type')
    op.drop_column('news', 'parser_source')
    op.create_table('news_to_base',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('news_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('news_to_base_ibfk_1')),
    sa.ForeignKeyConstraint(['tag_id'], ['news_tags.id'], name=op.f('news_to_base_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('news_to_tags')
    # ### end Alembic commands ###
