"""initial tables

Revision ID: 9851ce128876
Revises: 21e2de69ed01
Create Date: 2026-06-20 14:19:33.128810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9851ce128876'
down_revision: Union[str, Sequence[str], None] = '21e2de69ed01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('docs_url', sa.String(length=255), nullable=True))
    op.add_column('brands', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('brands', 'logo_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('document', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('document', sa.Column('doc_type', sa.String(length=50), nullable=True))
    op.add_column('document', sa.Column('parser_source', sa.String(length=100), nullable=True))
    op.alter_column('document', 'model_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('document', 'file_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('document', 'source_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=True)
    op.create_unique_constraint(None, 'document', ['source_url'])
    op.drop_column('document', 'version')
    op.alter_column('equipment_category', 'icon',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('models', 'spec',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('models', 'image_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('reviews', 'rating',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column('reviews', 'rating',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('models', 'image_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('models', 'spec',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('equipment_category', 'icon',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('document', sa.Column('version', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document', type_='unique')
    op.alter_column('document', 'source_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('document', 'file_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('document', 'model_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('document', 'parser_source')
    op.drop_column('document', 'doc_type')
    op.drop_column('document', 'title')
    op.alter_column('brands', 'logo_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('brands', 'is_active')
    op.drop_column('brands', 'docs_url')
    # ### end Alembic commands ###
