"""initial tables

Revision ID: ed941b8b33b2
Revises: 9851ce128876
Create Date: 2026-06-21 15:58:22.072801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ed941b8b33b2'
down_revision: Union[str, Sequence[str], None] = '9851ce128876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=255), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('document', 'version_number')
    op.drop_column('document', 'is_latest')
    op.drop_column('document', 'file_url')
    op.drop_column('document', 'file_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('file_hash', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('document', sa.Column('file_url', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('document', sa.Column('is_latest', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('version_number', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('document_versions')
    # ### end Alembic commands ###
